workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "MotoServiceLog.xcodeproj"
        XCODE_SCHEME: "MotoServiceLog"
        BUNDLE_ID: "com.motoservicelog.app"
        APP_STORE_APP_ID: 0000000000
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.motoservicelog.app
      app_store_connect: STEWART HARRY
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo 0)
          agvtool new-version -all $((LATEST_BUILD + 1))
      - name: Build ipa for App Store
        script: xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
